# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: totally_lazy 0.0.10 ruby lib

Gem::Specification.new do |s|
  s.name = "totally_lazy"
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kingsley Hendrickse"]
  s.date = "2015-10-29"
  s.description = "Port of java functional library totally lazy to ruby"
  s.email = "kingsleyhendrickse@me.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/any.rb",
    "lib/functor.rb",
    "lib/generators.rb",
    "lib/option.rb",
    "lib/pair.rb",
    "lib/parallel/parallel.rb",
    "lib/parallel/processor_count.rb",
    "lib/predicates/compare.rb",
    "lib/predicates/conversions.rb",
    "lib/predicates/numbers.rb",
    "lib/predicates/predicates.rb",
    "lib/predicates/where.rb",
    "lib/predicates/where_processor.rb",
    "lib/sequence.rb",
    "lib/totally_lazy.rb",
    "lib/type_check.rb",
    "lib/utils.rb",
    "spec/functor_spec.rb",
    "spec/generators_spec.rb",
    "spec/option_spec.rb",
    "spec/pair_spec.rb",
    "spec/predicate_spec.rb",
    "spec/sequence_spec.rb",
    "spec/serialization_spec.rb",
    "spec/spec_helper.rb",
    "spec/type_check_spec.rb",
    "spec/util_spec.rb",
    "totally_lazy.gemspec"
  ]
  s.homepage = "http://github.com/kingsleyh/totally_lazy"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Port of java functional library totally lazy to ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<rspec_html_formatter>, ["~> 0.3.0"])
      s.add_development_dependency(%q<rake>, ["~> 10.3.2"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.0.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<rspec_html_formatter>, ["~> 0.3.0"])
      s.add_dependency(%q<rake>, ["~> 10.3.2"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.0.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<rspec_html_formatter>, ["~> 0.3.0"])
    s.add_dependency(%q<rake>, ["~> 10.3.2"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
  end
end

